[build]
  command = "echo 'This is a Python Streamlit app - deploy to Render, Railway, or Heroku instead'"
  publish = "."

[[redirects]]
  from = "/*"
  to = "https://your-app-name.onrender.com/:splat"
  status = 301
  force = true 