services:
  - type: web
    name: llm-code-analyzer
    env: python
    repo: https://github.com/arun3676/ai-code-analyzer.git
    branch: master
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run matrix_app.py --server.port=$PORT --server.address=0.0.0.0
    plan: free
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: DEEPSEEK_API_KEY
        sync: false 